#@ load("@ytt:data", "data")
apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: #@ data.values.name
spec:
  git:
    url: #@ data.values.url
    ref:
      branch: #@ data.values.branch